apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-apk
spec:
  replicas: 10
  selector:
    matchLabels:
      app: flask-apk  
  template:
    metadata:
      labels:
        app: flask-apk
    spec:
      containers:
        - name: flask-apk
          image: mdirshaq/flask-web-app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    app: flask-apk  
  ports:
    - port: 5000
      targetPort: 5000
